### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by geekodour** [geekodour/github-blog-api#5]
@CodeDotJS  can you take a look at why the travis build is failing, it seems to be working. the test file seems to be passing all test on local machine.

**Comment by CodeDotJS** [comment]
@geekodour I checked it yesterday and the build only failed for `node v6` but there wasn't any issue with the code so when I checked the log file it showed that some process was left incomplete and due to that the build failed. 

So, I just restarted the build and it passed - check it [`here`](https://travis-ci.org/geekodour/github-blog-api). 

The only problem is - might be due to some caching shit or whatever, Travis isn't updating the build image.
